osx_image: xcode8.1
language: objective-c
script:
    - xcodebuild -project Demo.xcodeproj -scheme Tests -destination 'platform=iOS Simulator,name=iPhone 6' test | xcpretty
notifications:
email: false
